# Generated by Django 3.0.2 on 2020-02-06 17:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name_plural': 'People',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Publisher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Thesis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('pub_year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('abstract', models.TextField()),
                ('uri', models.URLField()),
                ('file_url', models.URLField()),
                ('language', models.CharField(choices=[('en', 'English'), ('vi', 'Vietnamese'), ('', 'Unknown')], default='', max_length=10)),
                ('keywords', models.CharField(max_length=500)),
                ('advisor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advisor', to='UTDVN_database.Person')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='author', to='UTDVN_database.Person')),
                ('publisher', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='UTDVN_database.Publisher')),
            ],
            options={
                'verbose_name_plural': 'Theses',
                'ordering': ['title'],
            },
        ),
        migrations.AddConstraint(
            model_name='thesis',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique_thesis'),
        ),
        migrations.AddConstraint(
            model_name='thesis',
            constraint=models.CheckConstraint(check=models.Q(pub_year__lte=2020), name='pub_year_lte_now'),
        ),
    ]
