# Generated by Django 3.0.2 on 2020-02-10 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('UTDVN_database', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thesis',
            name='advisor',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='author',
        ),
        migrations.RemoveField(
            model_name='thesis',
            name='publisher',
        ),
        migrations.DeleteModel(
            name='Person',
        ),
        migrations.DeleteModel(
            name='Publisher',
        ),
        migrations.DeleteModel(
            name='Thesis',
        ),
    ]
