language: python

python:
  - 3.8

services: 
  - mysql

install:
  - pip install -r requirements.txt

before_script:
  - mysql -e 'CREATE DATABASE test;' -u root

script: 
  - bash ./fixs/web_haystack/script.sh
  - python UTDVN_backend/manage.py test UTDVN_backend.tests
  - python UTDVN_backend/manage.py test UTDVN_crawler.tests