language: python

python:
  - 3.8

services: 
  - docker

install:
  - docker-compose up -d solr web

script:
  - docker-compose exec web python UTDVN_backend/manage.py test UTDVN_backend/UTDVN_database
  - docker-compose exec web python UTDVN_backend/manage.py test UTDVN_crawler

notifications:
  email:
    on_success: change
    on_failure: change