version: '3.7'

services:
  db:
    build:
      context: .
      dockerfile: db.Dockerfile
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utdvn
    ports:
      - "3306:3306"

  solr:
    build:
      context: .
      dockerfile: solr.Dockerfile
    ports:
     - "8983:8983"
    entrypoint: [
      "/opt/docker-solr/scripts/start-solr.sh",
      "thesis",
    ]

  web:
    image: newluminous/utdvn
    command: bash scripts/start-web.sh
    volumes:
      - .:/home/utdvn
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
      
volumes:
  db_data: