version: '3.7'

services:
  db:
    image: mysql:8.0
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - /db_cnf/mycustom.cnf:/etc/mysql/conf.d/custom.cnf
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utdvn
    ports:
      - "3306:3306"
      
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
    ports:
      - "8080:80"
    links:
      - db

  solr:
    image: solr:8.4
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

  web:
    image: newluminous/utdvn
    container_name: utdvn_web
    command: python3 UTDVN_backend/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/utdvn
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr
      
volumes:
  db_data: