version: '3.7'

services:
  db:
    image: mysql
    container_name: mysql
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: utdvn

  solr:
    image: solr
    ports:
     - "8983:8983"
    entrypoint:
      - docker-entrypoint.sh
      - solr-precreate
      - mycore

  web:
    build: .
    command: python3 UTDVN_backend/manage.py runserver 0.0.0.0:8000
    environment:
      DATABASE_HOST: mysql
      DATABASE_USER_NAME: root
      DATABASE_PASSWORD: root
    volumes:
      - .:/home/utdvn
    ports:
      - "8000:8000"
    depends_on:
      - db
      - solr

volumes:
  db_data